In [35]:
data = pd.read_csv(
    "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day24-standardization/Social_Network_Ads.csv"
)

data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [36]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])


data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [37]:
from sklearn.model_selection import train_test_split

X = data.iloc[:, :-1]
y = data.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

Standardirdization is a technique used to transform the data into a common scale, making it easier to compare and analyze different features. It is performed using the StandardScaler class from the sklearn.preprocessing module. Here's an example of how to use StandardScaler to standardize the data:"""

from sklearn.preprocessing import StandardScaler

In [38]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [39]:
columns = X.columns
X_train_scaled = pd.DataFrame(X_train_scaled, columns=columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=columns)

X_train_scaled

      User ID    Gender       Age  EstimatedSalary
0   -0.373119  1.025320  1.922950         2.146016
1   -1.223199 -0.975305  2.020161         0.378719
2   -0.596909 -0.975305 -1.382215        -0.432499
3    0.212616 -0.975305 -1.187794        -1.011940
4    0.641324 -0.975305  1.922950        -0.925024
..        ...       ...       ...              ...
315 -1.017940 -0.975305  0.950843        -1.156800
316  1.254105  1.025320 -0.896162        -0.780164
317 -1.415714  1.025320 -0.215686        -0.519415
318  1.208229 -0.975305 -1.090583        -0.461471
319  1.468091 -0.975305 -1.187794         1.392742

[320 rows x 4 columns]

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, r2_score, mean_squared_error

lr = LogisticRegression()
lr.fit(X_train, y_train)

# print(X_train)
y_pred = lr.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("R2 score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

Accuracy: 0.9125
R2 score: 0.5611285266457682
MSE: 0.0875

In [ ]:
lr_scaled = LogisticRegression()
lr_scaled.fit(X_train_scaled, y_train)

# print(X_train_scaled)
y_pred = lr_scaled.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("R2 score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

      User ID    Gender       Age  EstimatedSalary
0   -0.373119  1.025320  1.922950         2.146016
1   -1.223199 -0.975305  2.020161         0.378719
2   -0.596909 -0.975305 -1.382215        -0.432499
3    0.212616 -0.975305 -1.187794        -1.011940
4    0.641324 -0.975305  1.922950        -0.925024
..        ...       ...       ...              ...
315 -1.017940 -0.975305  0.950843        -1.156800
316  1.254105  1.025320 -0.896162        -0.780164
317 -1.415714  1.025320 -0.215686        -0.519415
318  1.208229 -0.975305 -1.090583        -0.461471
319  1.468091 -0.975305 -1.187794         1.392742

[320 rows x 4 columns]
Accuracy: 0.925
R2 score: 0.6238244514106583
MSE: 0.075